package com.tju.elm_bk.service;

import com.tju.elm_bk.exception.APIException;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.springframework.web.multipart.MultipartFile;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;
import java.util.UUID;

/**
 * Stores user-uploaded images in a local, persistent directory.
 *
 * <p>Neither the browser-supplied MIME type nor the original filename is trusted.
 * The extension is derived from the real file signature and the stored filename is
 * generated by the server.</p>
 */
@Service
public class ImageStorageService {
    public static final long MAX_IMAGE_SIZE = 5L * 1024 * 1024;

    private final Path uploadRoot;

    public ImageStorageService(@Value("${app.upload.directory:./uploads}") String uploadDirectory) {
        this.uploadRoot = Path.of(uploadDirectory).toAbsolutePath().normalize();
    }

    public String storeImage(MultipartFile file) throws IOException {
        if (file == null || file.isEmpty()) {
            throw new APIException("请选择需要上传的图片");
        }
        if (file.getSize() > MAX_IMAGE_SIZE) {
            throw new APIException("图片大小不能超过5MB");
        }

        byte[] content = file.getBytes();
        if (content.length > MAX_IMAGE_SIZE) {
            throw new APIException("图片大小不能超过5MB");
        }
        String extension = detectImageExtension(content);
        if (extension == null) {
            throw new APIException("仅支持 JPG、PNG 或 WebP 图片");
        }

        Files.createDirectories(uploadRoot);
        String storedName = UUID.randomUUID() + extension;
        Path destination = uploadRoot.resolve(storedName).normalize();
        if (!destination.getParent().equals(uploadRoot)) {
            throw new APIException("图片存储路径不合法");
        }
        Files.write(destination, content, StandardOpenOption.CREATE_NEW);
        return "/uploads/" + storedName;
    }

    static String detectImageExtension(byte[] bytes) {
        if (bytes.length >= 3
                && (bytes[0] & 0xff) == 0xff
                && (bytes[1] & 0xff) == 0xd8
                && (bytes[2] & 0xff) == 0xff) {
            return ".jpg";
        }
        if (bytes.length >= 8
                && (bytes[0] & 0xff) == 0x89
                && bytes[1] == 0x50 && bytes[2] == 0x4e && bytes[3] == 0x47
                && bytes[4] == 0x0d && bytes[5] == 0x0a
                && bytes[6] == 0x1a && bytes[7] == 0x0a) {
            return ".png";
        }
        if (bytes.length >= 12
                && bytes[0] == 'R' && bytes[1] == 'I' && bytes[2] == 'F' && bytes[3] == 'F'
                && bytes[8] == 'W' && bytes[9] == 'E' && bytes[10] == 'B' && bytes[11] == 'P') {
            return ".webp";
        }
        return null;
    }
}
